### PR TITLE
Updated PrefabLoader to automatically process bundles

### PR DESCRIPTION
**Pull request by Frityet**

### CODE REVIEW

**Comment by nrgill28** [comment]
This is not behavior that I believe is desirable. Why force the user to re-process a bundle every time they want to load something from it?

**Comment by Frityet** [comment]
Without having the bundle be processed, the scripts are completely broken

**Comment by Frityet** [comment]
or do you mean the deletion then reprocessing?

**Comment by nrgill28** [comment]
That's why you do it before using the tool...

**Comment by Frityet** [comment]
I deleted the file to account for updates, where if I had just used the same file again then over an update the user would have to delete the old bundle

**Comment by nrgill28** [comment]
I have other plans which would make this unnecessary anyway.

**Pull request closed without merging**
